### ISSUE TITLE
License not stated explicitly

### ISSUE THREAD

**Issue by vn971** [stemjail/stemjail#3]
The project does not seem to have a license, currently.

A file named `COPYING.txt` is in the repo, but this is just a quotation (copy) of GPL. Please read the bottom of COPYING.txt file, where it says:

> How to Apply These Terms to Your New Programs

In short, you should add at least some short info to README or a separate LICENSE.txt file, really saying that this project is GPL.

**Comment by l0kod** [comment]
Like said the [howto](https://www.gnu.org/licenses/gpl-howto.en.html), every source file have a license header. Moreover each _Cargo.toml_ (metadata file) have the license. There is no need for an extra _LICENSE.txt_ ("In GNU programs the license is usually in a file called COPYING.") but I should probably add a sentence about the license in the README.

**Comment by vn971** [comment]
Oh, I didn't notice that. Thanks for the explanation! Notion of the license in README may help.
