### ISSUE TITLE
No domain found

### ISSUE THREAD

**Issue by pchaigno** [stemjail/stemjail#4]
I get the following error when I try to launch StemJail with vi:

```
DEBUG:stemjail::srv: Portal got request: Run(DoRun(RunRequest { profile: None, command: ["./tools/env.sh", "/usr/bin/vi"], stdio: true }))
ERROR:stemjail::srv::manager: No domain found for Cmd(["./tools/env.sh", "/usr/bin/vi"])
ERROR:stemjail::srv: Error handling client: No domain found
```

The command I used:

```
/stemjail/stemjail$ ./tools/kage.sh run -t -- ./tools/env.sh /usr/bin/vi
```

Did I forget to configure/install something?

**Comment by l0kod** [comment]
You need to use absolute paths (e.g. ``pwd`/tools/env.sh /usr/bin/vi`).

**Comment by pchaigno** [comment]
Already tried ;)
I'm now using absolute paths for the two commands and every parameters.

**Comment by l0kod** [comment]
OK, so your profiles must allows both paths.

**Comment by l0kod** [comment]
Or at least one profile…

**Comment by pchaigno** [comment]
Okay... how do I do that?

**Comment by l0kod** [comment]
Take a look at the [profiles](https://github.com/stemjail/stemjail/tree/master/config/profiles) directory.

A profile must contains something like this:

```
[[fs.bind]]
path = "/your/stemjail/path"

[[fs.bind]]
path = "/usr"
```

And of course every path needed to run properly your application (e.g. /lib, /etc…).

**Comment by pchaigno** [comment]
Okay, it works. I forgot to configure these in my profiles.
Maybe this should be explained in the README or in the Wiki though. It's really not obvious currently :/
